# Generated by Django 5.0.7 on 2024-07-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_projects_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.category"
            ),
        ),
    ]
